### ISSUE TITLE
issues I met: distorted face etc

### ISSUE THREAD

**Issue by ThornbirdZhang** [magic-research/magic-animate#120]
Magic-animate is a great  project! based on my tryings, these two ways might lead to better results
1. photo and driver video are both 1:1, for example 1024x1024.
2. human in photo has the samilar path with driver video.

now, my issues are 
1. distorted face, esp. drver video has different portion or angle from that in photo. for instance, the man in driver video is fat, but the photo is thin. the same thing happens for different face angle.
2. hat, long hair and something like these also make trouble.
3. fingers seems funny. 
is there any way to alleviate them?

any suggestion is highly appreciated.  
![image](https://github.com/magic-research/magic-animate/assets/49382950/6e69d297-62f4-47f4-8f43-339077cd4584)

**Comment by zcxu-eric** [comment]
Hi, thanks for your interest. MagicAnimate is acutally not perfect and we are still working on it for improvement.
