### ISSUE TITLE
# Copyright 2023 ByteDance and/or its affiliates.

### ISSUE THREAD

**Issue by ThornbirdZhang** [magic-research/magic-animate#121]
is this one private codebase  of bytedance? 

# Copyright 2023 ByteDance and/or its affiliates.
#
# Copyright (2023) MagicAnimate Authors
#
# ByteDance, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from ByteDance or
# its affiliates is strictly prohibited.

**Comment by zcxu-eric** [comment]
Hi, please refere to our license.
