### ISSUE TITLE
non-square aspect ratios

### ISSUE THREAD

**Issue by ddpasa** [magic-research/magic-animate#129]
If I understand the animation pipeline construction correctly, the input video and picture is rescaled to a square shape before being processed by the pipeline: https://github.com/magic-research/magic-animate/blob/main/magicanimate/pipelines/animation.py#L177  This means that if you pass a picture or densepose video that is not square, then horrible aspect ratio deformations occur.

1. Is it possible to remove this requirement?  If we adjust animation.py so to handle non-square aspect rations, would the underlying model be able to handle it?

2. If the answer to the above question is no, then what's the recommended strategy for non-square inputs?  It's easy to crop photos to be square, but are these libraries that can take a non-square densepose video and make it square?

Thanks!

**Comment by zcxu-eric** [comment]
Hi, the answer is no, this library was only developed on square videos and all the inputs should be square.

**Comment by ddpasa** [comment]
Thanks @zcxu-eric for the reply.  Is there a way to convert non-square densepose vides to square ones by adding more padding around the video?

**Comment by zcxu-eric** [comment]
> Thanks @zcxu-eric for the reply. Is there a way to convert non-square densepose vides to square ones by adding more padding around the video?

Hi, of course, it is possible. We tried to pad non-square images into square using numpy 'edge' padding.
