### ISSUE TITLE
the more details for computing FID

### ISSUE THREAD

**Issue by Yongssss** [magic-research/magic-animate#133]
Do you compute FID between 100 generated images and the corresponding 100 real images for each video, and then average it over all videos? Or directly compute FID between all generated images (100 x the number of videos) and real images (100 x the number of videos)?

**Comment by zcxu-eric** [comment]
Hi, we compute FID between all generated images and gt images.

**Comment by Yongssss** [comment]
> Hi, we compute FID between all generated images and gt images.

I sincerely appreciate your reply. Do you calculate FVD between all generated images and gt images?

**Comment by Yongssss** [comment]
> > Hi, we compute FID between all generated images and gt images.
> 
> I sincerely appreciate your reply. Do you calculate FVD between all generated images and gt images?

I know many methods use 16 frames as a duration to extract 3D features, but I do not determine how many frames you use a unit to extract 3D features.

**Comment by zcxu-eric** [comment]
> > > Hi, we compute FID between all generated images and gt images.
> > 
> > 
> > I sincerely appreciate your reply. Do you calculate FVD between all generated images and gt images?
> 
> I know many methods use 16 frames as a duration to extract 3D features, but I do not determine how many frames you use a unit to extract 3D features.

We compute FVD betweem all the generated videos and gt videos, it's calculated based on 16 frames.

**Comment by Yongssss** [comment]
> > > > Hi, we compute FID between all generated images and gt images.
> > > 
> > > 
> > > I sincerely appreciate your reply. Do you calculate FVD between all generated images and gt images?
> > 
> > 
> > I know many methods use 16 frames as a duration to extract 3D features, but I do not determine how many frames you use a unit to extract 3D features.
> 
> We compute FVD betweem all the generated videos and gt videos, it's calculated based on 16 frames.

Thanks for your rapid reply again.
