### ISSUE TITLE
the head has deformed deeply.

### ISSUE THREAD

**Issue by PseudoProgrammer** [magic-research/magic-animate#134]
i upload my picture and the pose semantic map transformed from video (named "科目三") using https://www.pose.rip, and the result have two problems, 1) the head has deformed deeply. 2) body has deformed a little. 
 
so what's the problem, and how can i optimize this result? thanks 

![magic-animate_error](https://github.com/magic-research/magic-animate/assets/9998763/e4769a64-5afe-4206-b11d-c24e7501ce27)

**Comment by PseudoProgrammer** [comment]
@zcxu-eric  could you give me some advice？thanks

**Comment by PseudoProgrammer** [comment]
the human of this picture is cropped here , but it is complete when i upload this picture

**Comment by zcxu-eric** [comment]
I believe we have already discussed this issue.
