### ISSUE TITLE
Can this project only run on the linux platform?

### ISSUE THREAD

**Issue by HandsomeDong** [magic-research/magic-animate#137]
When I installed dependencies on Windows, many dependencies could not be installed. I try to find the installation package on pypi, it seems that there is only the Linux version of the installation package, such as:
nvidia-nccl-cu11==2.14.3
nvidia-cudnn-cu11==8.5.0.96
![微信截图_20240112011852](https://github.com/magic-research/magic-animate/assets/49794748/0b8df0db-79d0-481d-a06a-4b4cfec42fe4)
![微信截图_20240112012006](https://github.com/magic-research/magic-animate/assets/49794748/71d2d15d-5053-4c75-81c5-18dc768d6b96)

**Comment by bd233** [comment]
I also discovered this problem，就很呆

**Comment by bd233** [comment]
here: https://github.com/sdbds/magic-animate-for-windows/blob/main/requirements-windows.txt

**Comment by HandsomeDong** [comment]
> here: https://github.com/sdbds/magic-animate-for-windows/blob/main/requirements-windows.txt

非常感谢！
