### ISSUE TITLE
error loading script: animate.py, modulenotfounderror: no module named 'diffusers.modeling_utils'

### ISSUE THREAD

**Issue by gexmbla** [magic-research/magic-animate#140]
![problem1](https://github.com/magic-research/magic-animate/assets/155698400/13fff899-1868-4ca4-b418-59691974b798)

I have installed stable diffusion with no errors before. now this error shows up. I guess it came with the auto update. can anyone help fix ... ty.

**Comment by gexmbla** [comment]
![problem2](https://github.com/magic-research/magic-animate/assets/155698400/3e6fb86e-7d34-4deb-a763-c899cbe0d5d8)
It says submit this to github for debugging purposes ...

**Comment by zcxu-eric** [comment]
Hi, please refer to #15 for windows installation.
