### ISSUE TITLE
Question of Training Tiktok Dataset

### ISSUE THREAD

**Issue by Leoooo333** [magic-research/magic-animate#141]
![image](https://github.com/magic-research/magic-animate/assets/72211694/44429fb3-f36e-44ab-92e5-acae4eb80e22)
I download the TikTok dataset from https://www.yasamin.page/hdnet_tiktok. There are 340 videos in it, while your paper mentioned it have 350 videos. And also I can't find these three videos from the dataset. Did you trian on other dance videos? Thanks.

**Comment by zcxu-eric** [comment]
Hi, please download the TikTok dataset released by [DisCo](https://github.com/Wangt-CN/DisCo), they collected some sequences for testing.
