### ISSUE TITLE
the code of computing PSNR in the Disco repository is wrong

### ISSUE THREAD

**Issue by Yongssss** [magic-research/magic-animate#146]
The Disco code of computing PSNR as follows is wrong:
https://github.com/Wangt-CN/DisCo/blob/8538889c9ee9edd8dd43ffee182d1a91ce7a9828/tool/metrics/ssim_l1_lpips_psnr.py#L13.
![image](https://github.com/magic-research/magic-animate/assets/48432038/229bc98d-2b7f-49e5-a346-eab5ab7adcd1)

The accurate code is mse = np.mean((original/1.0 - compressed/1.0) ** 2) instead of mse = np.mean((original - compressed) ** 2) , because original and compressed images are uint8 in their code,  and (original - compressed) * * 2 will cause numerical overflow.

**Comment by Yongssss** [comment]
If you use their evaluation code of computing PSNR, please update your results.

**Comment by zcxu-eric** [comment]
Thanks for reminding, we will check this bug.
