### ISSUE TITLE
Details about computing FVD

### ISSUE THREAD

**Issue by S2DM** [magic-research/magic-animate#155]
Hey! I wonder how many generated videos you used to computed the FVD on TikTok dataset? Thanks!

**Comment by zcxu-eric** [comment]
Hi, please check issue #133

**Comment by Lanhaoran** [comment]
Thanks @zcxu-eric . I can learn from #133 that you used 16 frames of video to extract 3D feature, but I still don't know how many videos you generated to calculate FVD, is it consistent with the number of videos in validation dataset? As we know that the number of videos used to calculate the FVD score also has a large impact on the final FVD result.

**Comment by S2DM** [comment]
Thanks @zcxu-eric. I can learn from #133 that you used 16 frames of video to extract 3D feature, but I still don't know how many videos you generated to calculate FVD, is it consistent with the number of videos in validation dataset? As we know that the number of video used to calculate the FVD score also has a large impact on the final result.

**Comment by zcxu-eric** [comment]
> Thanks @zcxu-eric. I can learn from #133 that you used 16 frames of video to extract 3D feature, but I still don't know how many videos you generated to calculate FVD, is it consistent with the number of videos in validation dataset? As we know that the number of video used to calculate the FVD score also has a large impact on the final result.

Yes, all the videos in validation dataset.

**Comment by S2DM** [comment]
OK, Thanks for your reply!
