### ISSUE TITLE
Image-video joint training

### ISSUE THREAD

**Issue by Lanhaoran** [magic-research/magic-animate#156]
Hello! I noticed that the image-video joint training strategy was used in the training stage and the images are from the LAION-400M dataset as mentioned in the paper . I would like to know how you selected human pictures as training data from LAION-400M dataset during the training process? And what is the approximate amount of the image data? Thank you!

**Comment by zcxu-eric** [comment]
Hi, we used an internal version selected by other colleagues and the total about is about 1 million. We actually find that LAION can improve the clothes details but will not affect the overall results too much, you can start training without it.

**Comment by Lanhaoran** [comment]
Thanks for your response. I am also interested to know if there are any plans to release this portion of the dataset？

**Comment by zcxu-eric** [comment]
We have no plan for the release because this dataset is built on top of some internal libraries.
