### ISSUE TITLE
(IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MagicAnimate

### ISSUE THREAD

**Issue by ChenghuFanTiger** [magic-research/magic-animate#158]
I'm sure the files(14.6GB) of path: \models\MagicAnimate are correct: 
appearance_encoder/config.json 
appearance_encoder/diffusion_pytorch_model.safetensors 
control_v11p_sd15_openpose/config.json 
control_v11p_sd15_openpose/diffusion_pytorch_model.safetensors 
densepose_controlnet/config.json 
densepose_controlnet/diffusion_pytorch_model.safetensors 
sd-vae-ft-mse/config.json 
sd-vae-ft-mse/diffusion_pytorch_model.safetensors 
stable-diffusion-v1-5/text_encoder/config.json 
stable-diffusion-v1-5/text_encoder/model.safetensors 
stable-diffusion-v1-5/tokenizer/merges.txt 
stable-diffusion-v1-5/tokenizer/special_tokens_map.json 
stable-diffusion-v1-5/tokenizer/tokenizer_config.json 
stable-diffusion-v1-5/tokenizer/vocab.json 
stable-diffusion-v1-5/unet/config.json 
stable-diffusion-v1-5/unet/diffusion_pytorch_model.bin 
temporal_attention/temporal_attention.ckpt

When I restart comfyui, the red nodes appears:
![111](https://github.com/magic-research/magic-animate/assets/164842160/1075a322-4886-4e61-8975-e55124c58ed9)

When loading the graph, the following node types were not found:
MagicAnimateModelLoader
MagicAnimate
Nodes that have failed to load will show as red on the graph.

**Comment by zcxu-eric** [comment]
Hi, the comfyUI is not developed and maintained by us, please kindly find solutions from the developers.
