### ISSUE TITLE
Dense pose video for Portrait Video

### ISSUE THREAD

**Issue by alfredplpl** [magic-research/magic-animate#16]
Great work!
I move this work.
I can create a portrait video for TikTok by changing the code.

https://github.com/magic-research/magic-animate/assets/3625196/2e75cebd-0dc5-47b2-b1df-e07423489fba

However, the video is weird because the dense pose video is square.
How can I create the portrait dense pose video for TikTok?
Thanks in advance.

**Comment by FurkanGozukara** [comment]
I was expecting this was implemented in the repo but it is not sadly

**Comment by zcxu-eric** [comment]
Hello guys,  thanks for your interest.

If you are asking about how to generate customized DensePose motion sequence, I think this #18 issue can answer your question.

**Comment by alfredplpl** [comment]
Thank you. I will try detectron2.
