### ISSUE TITLE
Fix broken model links

### ISSUE THREAD

**Issue by przvlprd** [magic-research/magic-animate#2]
The links for the base model [StableDiffusion V1.5](https://github.com/magic-research/magic-animate/blob/main/runwayml/stable-diffusion-v1-5) and [MSE-finetuned VAE](https://github.com/magic-research/magic-animate/blob/main/stabilityai/sd-vae-ft-mse) are broken, please provide the correct links to HuggingFace.

**Comment by przvlprd** [comment]
Fixed links:
[StableDiffusion V1.5](https://huggingface.co/runwayml/stable-diffusion-v1-5)

[MSE-finetuned VAE](https://huggingface.co/stabilityai/sd-vae-ft-mse)

**Comment by igorriti** [comment]
I made a pull request with the links fixed! 
#3

**Comment by zcxu-eric** [comment]
Thans you all for the help, we've fixed this error.

**Comment by Nixizfan** [comment]
Why can't I open the link between these two models?（StableDiffusion V1.5 and MSE-finetuned VAE.）
