### ISSUE TITLE
MagicAnimate Online Demo

### ISSUE THREAD

**Issue by Arjun284** [magic-research/magic-animate#25]
Thanks for the amazing project ❤️
I made an online demo for more people to enjoy this awesome work 🎉
- https://chromox.alkaidvision.com

btw, I made some changes and it now supports arbitrary aspect ratio:
<img width="300" alt="image" src="https://github.com/magic-research/magic-animate/assets/53437351/cb28f832-9b8d-4311-aa7a-019f4c3a66d0">

Again, really amazing idea and great work👍

**Comment by zcxu-eric** [comment]
Thanks for the interest.
