### ISSUE TITLE
Custom input data error

### ISSUE THREAD

**Issue by antoinerrr** [magic-research/magic-animate#27]
Hey, thanks for the release it's quite amazing having access to this for free ! Quick question tho, I'm having this error when using my own input image (works fine with the exemple data) any idea ?

```
torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [128, 3, 3, 3], expected input[1, 4, 512, 512] to have 3 channels, but got 4 channels instead
```

Thanks !

**Comment by antoiner77** [comment]
I use one of the example, I just customised the input image.

**Comment by FurkanGozukara** [comment]
i have used this image it works. 512x512

installed via my [auto installer](https://www.patreon.com/posts/94098751) on windows 10 python 3.10.11 - venv

![ex_image](https://github.com/magic-research/magic-animate/assets/19240467/574b73f2-be50-494f-aa33-c2ac90501232)

https://github.com/magic-research/magic-animate/assets/19240467/c85ea92a-ae97-4b01-bd08-e77d7420e7ec

**Comment by antoiner77** [comment]
Converting it to jpg solved my issue

**Comment by hub3er** [comment]
> I want to take the densepose of a different video and transfer it. How do I get the densepose from the video? @FurkanGozukara

use this space on huggingface: https://huggingface.co/spaces/fffiloni/video2densepose

**Comment by zhangdanfeng888** [comment]
> Converting it to jpg solved my issue将其转换为jpg解决了我的问题

I have the same question, and my data is jpg file.

**Comment by gph1q** [comment]
> > Converting it to jpg solved my issue将其转换为jpg解决了我的问题
> 
> I have the same question, and my data is jpg file.
do you solve this question? thank you
