### ISSUE TITLE
Do you incorporate UV from DensePose?

### ISSUE THREAD

**Issue by areiner222** [magic-research/magic-animate#35]
Thanks for this incredible work!

For the motion representation, do you use the UV coordinates from the densepose representation or only the sequence of semantic part maps? If not, why not include the texture map as inputs for motion conditioning?

Thanks again!

**Comment by zcxu-eric** [comment]
Hi, thanks for your interest. We only used semantic part maps. We have tried UV coordinates but it seems hard to train a UV-based pose ControlNet.
