### ISSUE TITLE
My Dense Pose video uses more than 24 GB VRAM meanwhile yours uses like 10 GB why?

### ISSUE THREAD

**Issue by FurkanGozukara** [magic-research/magic-animate#38]
Here 1st one is your video

https://github.com/magic-research/magic-animate/assets/19240467/bc806e12-aeb0-4930-9591-8acfc993ba6e

And here second one is my own DensePose video

https://github.com/magic-research/magic-animate/assets/19240467/4c8a56fa-63ef-4792-ba48-d51c51acb3ff

Why mine is using more than 24 GB VRAM and causing OOM?

@zcxu-eric @jfzhang95

**Comment by Priestru** [comment]
Cus it's 9 times longer I guess.

**Comment by FurkanGozukara** [comment]
> Cus it's 9 times longer I guess.

i guess so testing

i also improved my dense pose too now much better


https://github.com/magic-research/magic-animate/assets/19240467/326051e1-d56c-4cd4-a206-7c4ac5aa69d9

**Comment by Priestru** [comment]
> i also improved my dense pose too now much better

Is it possible to segment smth with animeish proportions like this one?

https://github.com/magic-research/magic-animate/assets/108554892/5d3a8ab6-e8c5-4c2b-a1fb-4287c8124bf5

**Comment by FurkanGozukara** [comment]
> > i also improved my dense pose too now much better
> 
> Is it possible to segment smth with animeish proportions like this one? Densepose use facedetect so i wonder if it would work at all.
> 
> upd. Your 5 sec video works for me.
> 
>  output.mp4

tested

https://github.com/magic-research/magic-animate/assets/19240467/9a435c20-e183-4936-a7b2-ab86d7ffbd40

**Comment by Priestru** [comment]
> > > i also improved my dense pose too now much better
> > 
> > 
> > Is it possible to segment smth with animeish proportions like this one? Densepose use facedetect so i wonder if it would work at all.
> > upd. Your 5 sec video works for me.
> > output.mp4
> 
> tested
> 
>  test_dense.mp4

Yeah utter failure :DD

**Comment by FurkanGozukara** [comment]
I figured out reason : https://github.com/magic-research/magic-animate/issues/44
