### ISSUE TITLE
How to make it process 768 pixel?

### ISSUE THREAD

**Issue by FurkanGozukara** [magic-research/magic-animate#42]
i am giving 768 px image and 768x768 dense pose video but still getting 512px output

i have edited 

inference_config: "configs/inference/inference.yaml"
size: 768
L:    16
S:    1 
I:    0
clip: 0
offset: 0
max_length: null
video_type: "condition"
invert_video: false
save_individual_videos: true

save_individual_videos also not working

https://github.com/magic-research/magic-animate/assets/19240467/7dad0b8c-8ab3-4b62-9c34-f3f5565c86b6

![768](https://github.com/magic-research/magic-animate/assets/19240467/c1fbb713-70fa-4c1f-ad47-fcd30a93d053)

https://github.com/magic-research/magic-animate/assets/19240467/184f269f-5d70-4341-9412-a1b7b0ee105b

**Comment by alfredplpl** [comment]
You need to rewrite the demo code like this:

demo/gradio_animate.py
```python
    def read_video(video):
        size = (768, 768) #int(size)
        reader = imageio.get_reader(video)
        fps = reader.get_meta_data()['fps']
        assert fps == 25.0, f'Expected video fps: 25, but {fps} fps found'
        return video
    
    def read_image(image, size=512):
        return np.array(Image.fromarray(image).resize((768,768)))
```

demo/animate.py 
```python
            if motion_sequence.endswith('.mp4'):
                control = VideoReader(motion_sequence).read()
                # if control[0].shape[0] != size:
                control = [np.array(Image.fromarray(c).resize((768,768))) for c in control]
                control = np.array(control)

            #if source_image.shape[0] != size:
            source_image = np.array(Image.fromarray(source_image).resize((768,768)))
            H, W, C = source_image.shape

```

**Comment by FurkanGozukara** [comment]
@alfredplpl i changed demo already and removed size. so they are taken as raw

do i need to specifically give 768?

**Comment by FurkanGozukara** [comment]
I made 768 pixel but quality is even lower haha


https://github.com/magic-research/magic-animate/assets/19240467/106e1d7e-16c0-4e86-a901-e027ed3e8f84

**Comment by zcxu-eric** [comment]
That's what I expected, as I mentioned in #18, the quality will decrease because our appearance encoder was trained on 512.
