### ISSUE TITLE
Full Auto Installers For Windows & RunPod (so Linux too) Including Raw Video To DensePose Video

### ISSUE THREAD

**Issue by FurkanGozukara** [magic-research/magic-animate#44]
8 December 2023 Update

RunPod Instructions added as well

Gradio will not timeout and working

**I have spent over 24 hours to prepare all these scripts**

# You can download all from here : https://www.patreon.com/posts/94098751

-
-
-
-

![image](https://github.com/magic-research/magic-animate/assets/19240467/4b979aed-ed0a-40a4-82a5-7b2f485056d6)

![image](https://github.com/magic-research/magic-animate/assets/19240467/f5eed934-ecc3-4110-acaf-8320ad023d8b)

![image](https://github.com/magic-research/magic-animate/assets/19240467/f42d6cc5-b6c8-412a-8183-ed93a835f388)

Example 15 second DensePose I generated via my script

https://github.com/magic-research/magic-animate/assets/19240467/39362498-e131-40b1-a809-aad079708ce9

![image](https://github.com/magic-research/magic-animate/assets/19240467/a68105b9-a242-4975-983c-89391da8e94f)

**Full instructions** 

![a1](https://github.com/magic-research/magic-animate/assets/19240467/93b8416c-1aab-4022-8c80-de655dba77ec)

![a2](https://github.com/magic-research/magic-animate/assets/19240467/4f310558-5ce6-4281-aea1-d2e96ef30b0e)

![a3](https://github.com/magic-research/magic-animate/assets/19240467/d0a3d267-c3a6-4d77-a053-66faa9464e15)

![a4](https://github.com/magic-research/magic-animate/assets/19240467/439ffcc4-c4c8-4f84-8b51-9a409c00d7f4)

**Comment by hassantsyed** [comment]
lame that you're taking other people's work and putting it behind a paywall

**Comment by hassantsyed** [comment]
I decided that my previous comment was in poor taste.
I apologize.

**Comment by JuvenileLocksmith** [comment]
> I decided that my previous comment was in poor taste. I apologize.

Indeed, his business model is actually quite necessary given the trouble people suffer to get these things configured.

**Comment by friendlyFriend4000** [comment]
https://github.com/sdbds/magic-animate-for-windows

one click solution without a paywall

**Comment by FurkanGozukara** [comment]
8 December 2023 Update

RunPod Instructions added as well

Gradio will not timeout and working

I have spent over 24 hours to prepare all these scripts

You can download all from here : https://www.patreon.com/posts/94098751

**Comment by FurkanGozukara** [comment]
just updated again and now supports custom checkpoint loading

i made default model realistic vision v6

although i didnt see any difference

**Comment by FurkanGozukara** [comment]
made a new thread . added CodeFormer to restore faces and it is huge : https://github.com/magic-research/magic-animate/issues/85
