### ISSUE TITLE
Process is "Killed" after finishing

### ISSUE THREAD

**Issue by jygkh** [magic-research/magic-animate#53]
100%|███████████████████████████████████████████████████████████████████████████████████| 25/25 [08:31<00:00, 20.46s/it]100%|█████████████████████████████████████████████████████████████████████████████████| 112/112 [00:26<00:00,  4.16it/s]Killed

**Comment by FurkanGozukara** [comment]
i have no such error interesting 

16 GB is sufficient but depends on video duration

**Comment by OswaldoBornemann** [comment]
The same question.

**Comment by OswaldoBornemann** [comment]
I have tried this one, and it seems that the problem is solved. https://github.com/tloen/alpaca-lora/issues/60

```
change
demo.launch(share=True)
to
demo.queue().launch(share=True)
```
