### ISSUE TITLE
Request for Consideration: Inclusive Image Usage in Repository

### ISSUE THREAD

**Issue by Masa-99** [magic-research/magic-animate#72]
I hope this finds you well. I would like to bring to your attention a concern regarding the usage of images, particularly pictures of women, in your GitHub repository. There's a possibility that the individuals in these images may not have consented to their use.

In the spirit of promoting inclusivity and respecting individuals' privacy, I kindly request a review and consideration for alternative, more inclusive imagery in your repository. It's essential to ensure that the visual content aligns with ethical practices and fosters a welcoming environment for all contributors and users.

I appreciate your understanding and attention to this matter. If you have any questions or would like further clarification, please feel free to reach out! :)

**Comment by zcxu-eric** [comment]
Hi, thanks for reminding. We agree that the privacy issue is important. We have now removed images without copyrights and replaced them with AI-generated images.

**Comment by Masa-99** [comment]
@zcxu-eric thank you so much for taking my concerns seriously! Good luck with the project, the results are already impressive! :)
