### ISSUE TITLE
我增加了分辨率匹配，帧率匹配，支持自己写prompt

### ISSUE THREAD

**Issue by nicehero** [magic-research/magic-animate#88]
https://github.com/nicehero/magic-animate-for-colab

**Comment by zhangdanfeng888** [comment]
大佬，你这个新增的部分怎么使用呢？我看你这个链接里没有说明怎么使用分辨率和帧率匹配以及怎么自己写prompt

**Comment by nicehero** [comment]
> 大佬，你这个新增的部分怎么使用呢？我看你这个链接里没有说明怎么使用分辨率和帧率匹配以及怎么自己写prompt
分辨率和帧率匹配是自动的，根据你densepose视频的比例和帧率来，不需要设置
![1702551144180](https://github.com/magic-research/magic-animate/assets/4922143/850ed046-1aad-4bef-a35d-1263e364354b)

**Comment by dthcle** [comment]
请问有没有prompt使用的示例？
我尝试加了几个形容词但是生成的视频看起来没有什么变化

**Comment by Bluebang** [comment]
可以自己换模型吗？生成出来的人脸都是外国人

**Comment by nicehero** [comment]
> 可以自己换模型吗？生成出来的人脸都是外国人

可以换 修改configs/prompts/animation.yaml就行
但是没什么用，看之后Animate Anyone吧
