### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by slonce70** [magic-research/magic-animate#9]
Hi. When start project python3 -m demo.gradio_animate - have same error - 

Repository Not Found for url: https://huggingface.co/pretrained_models/stable-diffusion-v1-5/resolve/main/tokenizer/vocab.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

How to fix it and start a project!? Thanks

**Comment by przvlprd** [comment]
I made a pull request.
There were incomplete paths in one of the files.
#10

**Comment by zcxu-eric** [comment]
We have fixed this error in README, thank you guys.
