### ISSUE TITLE
ModuleNotFoundError: No module named 'magicanimate'

### ISSUE THREAD

**Issue by EriksUzans** [magic-research/magic-animate#90]
Hi, does anyone know how to fix this error ? I followed the instructions ,but still could not get it to work

PS S:\ai\magic-animate-for-windows> .\run_gui.ps1
Traceback (most recent call last):
  File "S:\ai\magic-animate-for-windows\demo\gradio_animate.py", line 17, in <module>
    from demo.animate import MagicAnimate
  File "S:\ai\magic-animate-for-windows\demo\animate.py", line 28, in <module>
    from magicanimate.models.unet_controlnet import UNet3DConditionModel
ModuleNotFoundError: No module named 'magicanimate'

**Comment by FurkanGozukara** [comment]
i have venv pip auto installer along with extra features such as auto dense pose maker and codeformer face improvement and video upscale 

https://github.com/magic-research/magic-animate/issues/85
