### ISSUE TITLE
安装教程不清晰

### ISSUE THREAD

**Issue by ZMote123** [magic-research/magic-animate#91]
建议梳理以下安装教程

**Comment by dvdcjw** [comment]
饭都要喂你嘴里了，还要怎么清晰

**Comment by ZMote123** [comment]
> 饭都要喂你嘴里了，还要怎么清晰

你有没有从零开始按照这个教程布置过？如果你布置过就会知道这个过程有多迷惑。我来告诉你迷惑在哪里
教程中说的是
![图片](https://github.com/magic-research/magic-animate/assets/69067753/1237094e-73cb-4320-b1a0-e6be645ab7be)
“Please download the pretrained base models for [StableDiffusion V1.5](https://huggingface.co/runwayml/stable-diffusion-v1-5) and [MSE-finetuned VAE](https://huggingface.co/stabilityai/sd-vae-ft-mse).
Download our MagicAnimate [checkpoints](https://huggingface.co/zcxu-eric/MagicAnimate).”
但是并没有说这几个文件夹如何放置，我是参考了https://github.com/EKI-INDRADI/magic-animate-for-windows-rnd-20231206中的介绍才正确放置的
![图片](https://github.com/magic-research/magic-animate/assets/69067753/dee96c42-070e-40c0-82b9-78a9b941117c)


另外闭上你的臭嘴，这种回答问题的方式很没有素质且让人瞧不起。你的傲慢从何而来？你不是这个项目的工作人员吧？是为了给这个项目招黑么？


直白一点
      你算个jb

**Comment by zcxu-eric** [comment]
Thanks for the suggestsions, we have updated README.
