### ISSUE TITLE
只有一个 GPU的时候，demo无法生成视频。

### ISSUE THREAD

**Issue by youngzs** [magic-research/magic-animate#99]
只有一个 GPU的时候，demo不会生成视频。
animate_dist.py 这个文件的 205行：if args.world_size > 0 and torch.cuda.device_count() > 1:

需要修改成 if args.world_size > 0 and torch.cuda.device_count() >= 1:

**Comment by wangwenqiao666** [comment]
有没有可能人家说的很清楚
![image](https://github.com/magic-research/magic-animate/assets/55267900/31494880-f7d7-4b8a-89a0-03929ff0c070)
